name: flutter_generic_state
description: A generic state management package for Flutter
version: 0.0.1
repository: https://github.com/satish-nep79/flutter_generic_state

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: